apiVersion: v1
kind: Secret
metadata:
  name: messaging-platform-secrets
  namespace: osop-messaging
type: Opaque
data:
  # Database Password (base64 encoded)
  DB_PASSWORD: cm9vdA==  # "root" in base64
  
  # Redis Password (base64 encoded)
  REDIS_PASSWORD: ""  # Empty for no password
  
  # RabbitMQ Password (base64 encoded)
  RABBITMQ_PASSWORD: YWRtaW4xMjM=  # "admin123" in base64
  
  # SMTP Credentials (base64 encoded)
  SMTP_USERNAME: ""  # Add your SMTP username
  SMTP_PASSWORD: ""  # Add your SMTP password
  
  # JWT Secret (base64 encoded)
  JWT_SECRET: bXlTZWNyZXRLZXlGb3JKV1RUb2tlbkdlbmVyYXRpb25UaGF0SXNBdExlYXN0MzJDaGFyYWN0ZXJzTG9uZw==  # "mySecretKeyForJWTTokenGenerationThatIsAtLeast32CharactersLong" in base64
  
  # AWS Credentials (base64 encoded)
  AWS_ACCESS_KEY: ""  # Add your AWS access key
  AWS_SECRET_KEY: ""  # Add your AWS secret key
  
  # Stripe Credentials (base64 encoded)
  STRIPE_SECRET_KEY: ""  # Add your Stripe secret key
  STRIPE_PUBLISHABLE_KEY: ""  # Add your Stripe publishable key
  STRIPE_WEBHOOK_SECRET: ""  # Add your Stripe webhook secret
  
  # Twilio Credentials (base64 encoded)
  TWILIO_ACCOUNT_SID: ""  # Add your Twilio account SID
  TWILIO_AUTH_TOKEN: ""  # Add your Twilio auth token
  TWILIO_PHONE_NUMBER: ""  # Add your Twilio phone number
  
  # WhatsApp Credentials (base64 encoded)
  WHATSAPP_ACCESS_TOKEN: ""  # Add your WhatsApp access token
  WHATSAPP_PHONE_NUMBER_ID: ""  # Add your WhatsApp phone number ID
  WHATSAPP_BUSINESS_ACCOUNT_ID: ""  # Add your WhatsApp business account ID
